### ISSUE TITLE
plan widgets for indexes

### ISSUE THREAD

**Issue by Davis245** [carsondrobe/Fellas#117]
Decide on how to present the initial spread index, the buildup index, and the fire weather index on the dashboard.

**Comment by Davis245** [comment]
I have been doing some exploring on how I could possibly present the fire indexes on the dashboard and I need some feedback on what path I should take.

Here's a paper prototype of a possible implementation that shows the relationship between the BUI and ISI to get the FWI. Also, in the paper drawing the scales go from 0-10 and 0-100, but the values for ISI and BUI can exceed those values so in the actual implementation I will look at past data to see what these values normally max out at in BC.

![Image](https://github.com/carsondrobe/Fellas/assets/97471058/90a269ba-0d92-4587-985d-0100f249a3c2)

That implementation is based off of the following table from the UBC ATSC 413 website.

![Image](https://github.com/carsondrobe/Fellas/assets/97471058/70e10cb0-0f09-4e68-92b5-067d221a917e)

Also, on that table I do not have access to see what table 4 consists of nor what the spring criteria is, so I would be working with some assumptions. However, I think it will be good enough for the purpose of this dashboard.

Alternatively, I could create visualization for the indexes similarly to how I created the visualizations for the moisture code where there is a coloured axis and an arrow. These visualizations would be based off of the scale of the following maps from the BC government website.

![Image](https://github.com/carsondrobe/Fellas/assets/97471058/6d746d11-b3ca-49c5-81eb-25a71d54a9c5)

![Image](https://github.com/carsondrobe/Fellas/assets/97471058/548314e6-c85b-40e2-a256-02b4cf3e9137)

![Image](https://github.com/carsondrobe/Fellas/assets/97471058/033f5873-fc73-4398-bb73-6fd6ca1abc5e)

**Comment by carsondrobe** [comment]
I like your paper prototype - however, that looks pretty difficult to turn into code. Do you have an idea of how you could implement it?

IF it's too difficult, I think consistency of creating visualizations like the other indices would work too.

**Comment by Davis245** [comment]
Okay, I think I'll just create them like the other ones. Thanks for the input.
