### ISSUE TITLE
Sequence Diagrams

### ISSUE THREAD

**Issue by robertyac** [carsondrobe/Fellas#20]
[5marks]

**Comment by carsondrobe** [comment]
![Image](https://github.com/carsondrobe/Fellas/assets/91719000/a75f5434-0154-4aa8-9191-83a8ff203ffd)

**Comment by carsondrobe** [comment]
please provide some feedback

**Comment by robertyac** [comment]
Looks great nice work! I would maybe extend the alternative/optional box to include the login and verify arrows since a user doesn't necessarily need to be logged in to view the dashboard.

**Comment by carsondrobe** [comment]
![Image](https://github.com/carsondrobe/Fellas/assets/91719000/4445c80c-93a7-429b-b47f-93bbc037be93)



Does this clarify what you mentioned Rob?

**Comment by robertyac** [comment]
Awesome

**Comment by abijeet-dhillon** [comment]
LGTM

**Comment by carsondrobe** [comment]
Will check with TA

**Comment by carsondrobe** [comment]
Adding an Admin Diagram and editing User

**Comment by carsondrobe** [comment]
![Image](https://github.com/carsondrobe/Fellas/assets/91719000/02f63420-6235-488f-8d05-6c5f01ff9069)



![Image](https://github.com/carsondrobe/Fellas/assets/91719000/5c4f0bce-e4b7-4e49-b604-88367f97f868)

**Comment by carsondrobe** [comment]
Admin and User seperated
