### ISSUE TITLE
DFD - Level 0 and 1

### ISSUE THREAD

**Issue by robertyac** [carsondrobe/Fellas#21]
[5marks]

You will need to model and analyze your use cases and requirements properly using the appropriate models with the appropriate level of granularity.  For the projects, at a minimum,  you will need to ensure that you have the appropriate sequence diagrams (supporting your use cases), as well as DFDs (you will need to have at least a level 0 and level 1).

**Comment by robertyac** [comment]
[Lucid chart link](https://lucid.app/lucidspark/4e361f4f-21f4-4cb7-935c-98f19b333b17/edit?viewport_loc=-1265%2C-271%2C5119%2C2538%2C0_0&invitationId=inv_ffaafff6-15a4-4216-bcd9-2bd4eac24d47)

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/d1d65c8a-9ede-457f-9b83-c552c452b508)



![Image](https://github.com/carsondrobe/Fellas/assets/112982183/19166142-d9de-4cda-b0b5-44f3a7a58899)

**Comment by carsondrobe** [comment]
Possible for Weather Info to go to Admin as well in Level 0?

**Comment by robertyac** [comment]
Good point, I think it needs to be reworked a little. Also in level 0 the system should be sending alerts to users not the admin. Admin create alerts that go to system and then alerts go to users?

**Comment by cmcahoon01** [comment]
Yeah maybe admin create alerts to System and System alerts users

**Comment by robertyac** [comment]
Updated level 0:



![Image](https://github.com/carsondrobe/Fellas/assets/112982183/6af0ec78-1757-4819-8105-b5347a31f903)
