### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by robertyac** [carsondrobe/Fellas#22]
[5marks]

You will need to model and analyze your use cases and requirements properly using the appropriate models with the appropriate level of granularity.  For the projects, at a minimum,  you will need to ensure that you have the appropriate sequence diagrams (supporting your use cases), and you will also need to include a class diagram for the different parts of the system.

**Comment by abijeet-dhillon** [comment]
[COSC310_Class_Diagram_V1.pdf](https://github.com/carsondrobe/Fellas/files/14351864/COSC310_Class_Diagram_V1.pdf)
Version 1 of COSC310 class diagram.

**Comment by robertyac** [comment]
I will do up another draft of the class diagram since I need it to make the models. I will ask for feedback on the diagram before starting the models.

**Comment by robertyac** [comment]
![Image](https://github.com/carsondrobe/Fellas/assets/112982183/4883dc5c-1037-4c31-b002-ac30e26ba5ed)

**Comment by robertyac** [comment]
- During the time that I was creating this diagram I was researching how to implement Django users and it looks like we can use the built in User model, it has built in security for password hashing, user differentiation and other features. 
-  Decided predictions don't make sense as an entity.
- Dashboard entity itself doesn't have much data other than what user type is accessing it to dynamically change what page gets shown to the user first (weather or fire related info)
- I realize some attributes and operations don't really make sense like the **layout attribute and operations**, it's late, these will have to be fixed most likely. 

Any feedback to change would be great so we can implement them soon 💯

**Comment by carsondrobe** [comment]
Looks good! off a quick read through I am curious how favouriteStations would be implemented with an int? Maybe would be better to have a List

**Comment by robertyac** [comment]
shoot yeah I'll fix that thanks

**Comment by carsondrobe** [comment]
And maybe User - Feedback relationship could be Many to Many 0..*, 0..* but depends on our intentions of feedback

**Comment by robertyac** [comment]
V2 of class diagram

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/ff1a1134-0691-465e-8259-05e15c40a60e)

**Comment by robertyac** [comment]
V2

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/7639dfdb-d247-4182-b4ec-702199c3ef88)

**Comment by robertyac** [comment]
V2

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/fb7da3d0-1b10-435f-9c8c-07978f7dfd62)

**Comment by Davis245** [comment]
I think the user feedback relation should be 1:N because any one piece of feedback belongs to only one user.

**Comment by cmcahoon01** [comment]
We also might want to have a class for the web scraper that gets the data. With a 1 to 1 on the dashboard to enable/disable it

**Comment by robertyac** [comment]
How and why would we make that into its own entity? The scraper doesn't actually store anything, I think in that case it's more appropriate for it to be on the sequence diagram than the class diagram.

**Comment by abijeet-dhillon** [comment]
I agree with Davis's comment on 1:N relation between user and feedback, other than that it looks good.

**Comment by robertyac** [comment]
Fixed 1:N relationship feedback between user and feedback 

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/6b95fb0a-6734-4b05-989b-6733d040089a)

**Comment by carsondrobe** [comment]
I'm happy with this

**Comment by robertyac** [comment]
Okay one more time: 

- added some attributes to align with the models I made
- removed getters and setters, not needed with Django
- polished it up


![Image](https://github.com/carsondrobe/Fellas/assets/112982183/cd3dfd90-96b4-4239-9a48-08d003b7773f)
