### ISSUE TITLE
Create Models for database

### ISSUE THREAD

**Issue by robertyac** [carsondrobe/Fellas#26]
dependent on 

- [x] #22

**Comment by robertyac** [comment]
view 27c43eb9a94c4eab95f965cc9e7acdc829046eb4 

Not sure if I need tests for models? Not sure how I would test them. I already tried them out on the Django admin site and from me just playing around adding data to different tables it seems to work well. 

Will write tests if possible but will need to look into that.

**Comment by carsondrobe** [comment]
I also have no clue about Database Testing. Nor HTML testing.

**Comment by Davis245** [comment]
In our use case diagram, we had the actors as users and administrators. In this database design, it says the users are common users and firefighters. I don't think we need to differentiate between common user and firefighter because they will have the same functionality; whereas, the admin will have the functionality that differs from the users like responding to feedback.

Also, I don't think you need to test this. Similarly, you don't need to write tests for HTML and CSS. You test them by making sure the output is correct.

**Comment by robertyac** [comment]
My idea behind giving our  **users** an attribute of common user or firefighting staff was that based on your paper prototype you made there are 2 main screens- a normal weather page and a fire weather page (with duff and index and stuff). Based on what user they select themselves to be when they register I thought we could potentially then show them that respective page as their "home" page when they log in, if that makes sense. 

It's simply just an attribute that is given to a user that extends the user model. Admin are still admin and users can **optionally** choose themselves to be normal users or firefighting staff (who may be more interested in page 2 of your paper prototype).

Admin functionality is built in natively to Django so there's no need for an admin model as we can access the admin page separately and the built in user model provides support for selecting what users are given access to admin functionality. 

I hope this clears it up?

**Comment by carsondrobe** [comment]
I agree with both of you guys. 

I think Users should have unrestricted access to all of the dashboards regardless of firefighter or general user designation. I think the idea for Dave's second page was you click that flame icon in the bottom right to jump down to Page 2. 

I also like the idea of having an attribute differentiating User vs Firefighter in case we decide to add some Firefighter-specific features down the line. Or perhaps we default the dashboard to display the "Weather" section and if the user opts into Advanced Statistics they can also view the "Fire" section.

Overall, I think it's a minor detail we can easily keep or remove later on if we decide.

**Comment by robertyac** [comment]
Also- all users are set to "common user" by default:

user_type = models.CharField(
        max_length=2,
        choices=USER_TYPE_CHOICES,
        **default=COMMON_USER,**
    )

And so this is more future proofing our project if we decide to do anything with this attribute. Otherwise it won't affect anything.

**Comment by Davis245** [comment]
Perfect. That clears up my confusion. I was not aware that Django has a built-in admin feature.

**Comment by robertyac** [comment]
Yea it's pretty convenient! you can access the admin page already after you do the `python manage.py run server` command and go to `http://localhost:8000/admin/` it should work
