### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by carsondrobe** [carsondrobe/Fellas#31]
You will need to develop a test plan that will detail the requirements for testing.

From the M3 assignment on Canvas: You will need to describe your test plan. That means, you should explain the current testing approaches your team is using and the future approaches your team will use.

**Comment by abijeet-dhillon** [comment]
Test Plan V1, make any adjustments or provide any feedback on how we can improve this (this is also available on the M3 google doc):

Our team is currently using the following testing approaches:

- **Structural (white-box) unit testing**
  Upon completion of each major feature, our team develops and runs tests on the testable code for that feature. These tests assure that the application will run smoothly under various test cases and allow us to test edge/hypothetical cases as well, ensuring our application will run in every scenario.

- **Dynamic verification**
  Our team performs dynamic verification by executing the system and observing its behaviour. This is done to reveal any errors which may be present.

- **Debugging**
  Upon using the testing approaches listed above, we then go through and debug our code to locate and repair errors that were found while testing. This ensures that we produce reliable and efficient code.

In the future, our team will implement the following testing approaches:

- **Performance (stress) testing**
  Before finishing development of our project, our team will perform a performance (stress) test on the application. This will involve increasing the system load to determine when performance becomes unacceptable and will help us gauge how much data/usage our application can withstand.

- **Product testing**
  Upon completion of our project’s core functionality, we will break our team into 2 groups who will each act as a SQA group. Each group will ensure that the product passes all requirements.

- **Acceptance testing**
  We will implement acceptance testing through multiple user tests of the product (user testing). This will allow users or potential users of the system to test the system in their own environment. This approach will let users report any errors/issues they may encounter while also providing a chance for critical feedback before the completion of our project.

**Comment by robertyac** [comment]
Maybe add something about 80% coverage on our tests? other than that LGTM!

**Comment by abijeet-dhillon** [comment]
> Maybe add something about 80% coverage on our tests? other than that LGTM!

Updated on the google doc. "Upon completion of each major feature, our team develops and runs tests on the testable code for that feature. These tests assure that the application will run smoothly under various test cases and allow us to test edge/hypothetical cases as well, ensuring our application will run in every scenario. We are also aiming for 80% coverage on our unit tests."

**Comment by carsondrobe** [comment]
LGTM
