### ISSUE TITLE
Implement the map by itself and get it running.

### ISSUE THREAD

**Issue by abijeet-dhillon** [carsondrobe/Fellas#46]
Try to implement the map with a download of leaflet files and see if you can customize the icons and put multiple markers on the map.

**Comment by abijeet-dhillon** [comment]
Created the map to run with a combination of local files (see leaflet folder in website folder) and using online links. Also changed the map marker icon to fire emojis, can be adjusted to anything later on though.

![Image](https://github.com/carsondrobe/Fellas/assets/112976240/26f52fb3-1adc-426b-bea1-ceec068be0e1)

Any feedback would be appreaciated!

**Comment by cmcahoon01** [comment]
🌡📻?

**Comment by abijeet-dhillon** [comment]
Discussed in scrum meeting. Marking as closed.
