### ISSUE TITLE
Get Data Set 

### ISSUE THREAD

**Issue by cmcahoon01** [carsondrobe/Fellas#5]
- [x] Find dataset.

**Comment by robertyac** [comment]
## Primary Data
Data Catalogue BC Gov: https://catalogue.data.gov.bc.ca/dataset/c16867a3-a7ac-4c07-9a3e-0325e66e29c0
Datamart the csv files: https://www.for.gov.bc.ca/ftp/HPR/external/!publish/BCWS_DATA_MART/

## Secondary **potential data**

Current Fire perimeters Data Catalogue BC Gov: https://catalogue.data.gov.bc.ca/dataset/fire-perimeters-current
