### ISSUE TITLE
Refactor File Directory/Naming for Easier Coding

### ISSUE THREAD

**Issue by carsondrobe** [carsondrobe/Fellas#51]
The current directory structure is hard to understand and makes it difficult to make any path references while coding.

**Comment by carsondrobe** [comment]
Makes it very difficult to reference static files. ie) there are two bc_weather_station_dashboard Folders Nested, one needs to be deleted

**Comment by robertyac** [comment]
One bc_weather_station_dashboard directory is the root directory of the Django project the other is the main configuration directory of our Django project. 

We can rename the outer bc_weather_station_dashboard directory to something like project_root, and the inner directory can stay the same. 

Here's some other useful info I found:
[Why Django has 2 project name folders ](https://stackoverflow.com/questions/24442768/why-does-django-name-2-folders-the-project-name)
[Django Project Structure: Guide](https://medium.com/django-unleashed/django-project-structure-a-comprehensive-guide-4b2ddbf2b6b8)

**Comment by carsondrobe** [comment]
I see, those links definitely helped, thanks. I think the project was made correctly with Site/bc_weather/bc_weather and then when we added it to GitHub it got further nested as Fellas/Site/bc_weather/bc_weather. So I think we could remove the Site directory and have Fellas/bc_weather/bc_weather? 

I can test that and make sure it doesn't create any errors with our current file referencing.
