### ISSUE TITLE
Create HTML for temperature widget

### ISSUE THREAD

**Issue by cmcahoon01** [carsondrobe/Fellas#52]

**Comment by robertyac** [comment]
I experimented and explored different options such as: 


![Image](https://github.com/carsondrobe/Fellas/assets/112982183/58c1f3cc-34b1-4007-8f38-206f08143280)

and tested other pre-built temperature gauges. 

I ended up just doing a more minimalist design with a bootstrap card I made myself:

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/7676e08a-8cfb-49b9-be7f-3686dec56ab0)

(the "Last updated at:" disappears if you are not hovered over it)
