### ISSUE TITLE
Create humidity widget

### ISSUE THREAD

**Issue by cmcahoon01** [carsondrobe/Fellas#54]

**Comment by robertyac** [comment]
Week 11: make a humidity widget that looks good and link it to the database so when a user clicks on a map it should update the widget.

I did some exploration and this is an idea of something similar to what I would like it to look like:

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/75b537a9-cf58-477b-84fd-9a3d1f30faca)

**Comment by robertyac** [comment]
What I ended up doing:

![Image](https://github.com/carsondrobe/Fellas/assets/112982183/19ae233c-56a9-4b80-8b6a-eb30df382a16)
